import { createGlobalTheme } from '@vanilla-extract/css';
import { vars as bentoVars } from '@buildo/bento-design-system';

const remBaseSize = 16;
const pixelToRem = (px: number) => `${px / remBaseSize}rem`;

const color = 'red'
const _color = 'red'

const _colors = {
  // TO DO check servono anche questi colori ( presi dal default )
  white: '#FFFFFF',
  black: '#000000',
  black_16: 'rgba(0, 0, 0, 0.16)',
  neutral05: '#ECEFF4',
  neutral10: '#DEE4ED',
  neutral20: '#CBD4E1',
  neutral30: '#B6C2D3',
  neutral50: '#728197',
  neutral60_30: 'rgba(82, 94, 111, 0.3)',
  neutral90: '#1A212B',
  informative40: '#2D7AE5',
  positive60: '#049B22',
  warning50: '#D66F00',
  negative40: '#CE0718',
  red10: '#FFBDCB',
  red30: '#FC5275',
  orange10: '#FFD4BC',
  orange30: '#FB8951',
  yellow10: '#FFF4B2',
  yellow30: '#FFD439',
  green10: '#DBF1BC',
  green30: '#A3D65C',
  jade10: '#B7F6D7',
  jade30: '#51E098',
  blue10: '#BCF2FF',
  blue30: '#51D0FB',
  indigo10: '#C0D3F9',
  indigo30: '#5F8CE6',
  violet10: '#DABEEA',
  violet30: '#A463C7',
  pink10: '#F8B0DA',
  pink30: '#E648A4',
};

const commonTheme = {
  fontFamily: {
    default: 'Lato, sans-serif',
  },
  fontSize: {
    bodySmall: pixelToRem(16),
    bodyMedium: pixelToRem(16),
    bodyLarge: pixelToRem(18),
    headlineSmall: pixelToRem(28),
    headlineMedium: pixelToRem(32),
    headlineLarge: pixelToRem(36),
    displaySmall: pixelToRem(36),
    displayMedium: pixelToRem(42),
    displayLarge: pixelToRem(48),
    labelSmall: pixelToRem(14),
    labelMedium: pixelToRem(16),
    labelLarge: pixelToRem(18),
    titleSmall: pixelToRem(24),
    titleMedium: pixelToRem(28),
    titleLarge: pixelToRem(32),
  },
  lineHeight: {
    bodySmall: pixelToRem(20),
    bodyMedium: pixelToRem(20),
    bodyLarge: pixelToRem(24),
    headlineSmall: pixelToRem(36),
    headlineMedium: pixelToRem(42),
    headlineLarge: pixelToRem(46),
    displaySmall: pixelToRem(40),
    displayMedium: pixelToRem(48),
    displayLarge: pixelToRem(52),
    labelSmall: pixelToRem(16),
    labelMedium: pixelToRem(20),
    labelLarge: pixelToRem(24),
    titleSmall: pixelToRem(32),
    titleMedium: pixelToRem(36),
    titleLarge: pixelToRem(42),
  },
  fontWeight: {
    body: '400',
    bodyStrong: '600',
    display: '500',
    headline: '500',
    label: '700',
    title: '600',
  },
  letterSpacing: {
    1: '0.01em',
    2: '0.02em',
  },
  space: {
    0: '0',
    4: '4px',
    8: '8px',
    16: '16px',
    24: '24px',
    32: '32px',
    40: '40px',
    80: '80px',
  },
  negativeSpace: {
    0: '0',
    negative4: '-4px',
    negative8: '-8px',
    negative16: '-16px',
    negative24: '-24px',
    negative32: '-32px',
    negative40: '-40px',
    negative80: '-80px',
  },
  radius: {
    4: '4px',
    8: '8px',
    16: '16px',
  },
};

createGlobalTheme(':root', bentoVars, {
  ...commonTheme,
  brandColor: {
    brandPrimary: color,
    brandSecondary: color,
    brandTertiary: color,
  },
  backgroundColor: {
    backgroundPrimary: color,
    backgroundSecondary: color,
    backgroundOverlay: color,
    backgroundPrimaryInverse: color,
    backgroundSecondaryInverse: color,
    backgroundInteractive: color,
    backgroundInteractiveOverlay: color,
    backgroundInformative: color,
    backgroundPositive: color,
    backgroundWarning: color,
    backgroundNegative: color,
    backgroundLightScrim: 'rgba(255, 255, 255, 0.8)',
    backgroundDarkScrim: 'rgba(13, 27, 53, 0.8)',
  },
  foregroundColor: {
    foregroundPrimary: color,
    foregroundSecondary: color,
    foregroundPrimaryInverse: color,
    foregroundSecondaryInverse: color,
    foregroundInteractive: color,
    foregroundInformative: color,
    foregroundPositive: color,
    foregroundWarning: color,
    foregroundNegative: color,
    foregroundDisabled: color,
  },
  textColor: {
    textPrimary: color,
    textSecondary: color,
    textPrimaryInverse: color,
    textSecondaryInverse: color,
    textInteractive: color,
    textInformative: color,
    textPositive: color,
    textWarning: color,
    textNegative: color,
    textDisabled: color,
  },
  interactiveBackgroundColor: {
    primarySolidEnabledBackground: color,
    primarySolidHoverBackground: color,
    primarySolidFocusBackground: color,
    primaryTransparentEnabledBackground: 'transparent',
    primaryTransparentHoverBackground: 'transparent',
    primaryTransparentFocusBackground: color,
    secondarySolidEnabledBackground: color,
    secondarySolidHoverBackground: color,
    secondarySolidFocusBackground: color,
    secondaryTransparentEnabledBackground: 'transparent',
    secondaryTransparentHoverBackground: 'transparent',
    secondaryTransparentFocusBackground: color,
    dangerSolidEnabledBackground: color,
    dangerSolidHoverBackground: 'transparent',
    dangerSolidFocusBackground: color,
    dangerTransparentEnabledBackground: 'transparent',
    dangerTransparentHoverBackground: 'transparent',
    dangerTransparentFocusBackground: color,
    disabledSolidBackground: color,
    disabledTransparentBackground: 'transparent',
  },
  interactiveForegroundColor: {
    primarySolidEnabledForeground: color,
    primarySolidHoverForeground: color,
    primarySolidFocusForeground: color,
    primaryTransparentEnabledForeground: color,
    primaryTransparentHoverForeground: color,
    primaryTransparentFocusForeground: color,
    secondarySolidEnabledForeground: color,
    secondarySolidHoverForeground: color,
    secondarySolidFocusForeground: color,
    secondaryTransparentEnabledForeground: color,
    secondaryTransparentHoverForeground: color,
    secondaryTransparentFocusForeground: color,
    dangerSolidEnabledForeground: color,
    dangerSolidHoverForeground: color,
    dangerSolidFocusForeground: color,
    dangerTransparentEnabledForeground: color,
    dangerTransparentHoverForeground: color,
    dangerTransparentFocusForeground: color,
    disabledSolidForeground: color,
    disabledTransparentForeground: color,
    linkEnabled: color,
    linkHover: color,
    linkFocus: color,
    linkDisabled: color,
    linkEnabledInverse: color,
    linkHoverInverse: color,
    linkFocusInverse: color,
    linkDisabledInverse: color,
  },
  outlineColor: {
    outlineInteractive: color,
    outlineDecorative: color,
    outlineContainer: color,
    outlineInputEnabled: color,
    outlineInputHover: color,
    outlineInputFocus: color,
    outlineInputDisabled: color,
    outlineInformative: color,
    outlinePositive: color,
    outlineWarning: color,
    outlineNegative: color,
  },
  dataVisualizationColor: {
    // TO DO check se i colori sono quelli giusti ( presi dal default )
    softGrey: color,
    softRed: _color,
    softOrange: _color,
    softYellow: _color,
    softGreen: _color,
    softJade: _color,
    softBlue: _color,
    softIndigo: _color,
    softViolet: _color,
    softPink: _color,
    brightGrey: color,
    brightRed: _color,
    brightOrange: _color,
    brightYellow: _color,
    brightGreen: _color,
    brightJade: _color,
    brightBlue: _color,
    brightIndigo: _color,
    brightViolet: _color,
    brightPink: _color,
  },
  boxShadow: {
    // TO DO check se i colori sono quelli giusti ( presi dal default )
    outlineInteractive: `inset 0px 0px 0px 1px ${_color}`,
    outlineInteractiveBottom: `inset 0px -1px 0px ${_color}`,
    outlineDecorative: `inset 0px 0px 0px 1px ${color}`,
    outlineDecorativeBottom: `inset 0px -1px 0px ${color}`,
    outlineContainer: `inset 0px 0px 0px 1px ${color}`,
    outlineInputEnabled: `inset 0px 0px 0px 1px ${color}`,
    outlineInputHover: `inset 0px 0px 0px 1px ${color}`,
    outlineInputFocus: `inset 0px 0px 0px 2px ${_color}`,
    outlineInputDisabled: `inset 0px 0px 0px 1px ${_color}`,
    outlineInformative: `inset 0px 0px 0px 1px ${color}`,
    outlinePositive: `inset 0px 0px 0px 1px ${color}`,
    outlineWarning: `inset 0px 0px 0px 1px ${color}`,
    outlineNegative: `inset 0px 0px 0px 1px ${color}`,
    outlineNegativeStrong: `inset 0px 0px 0px 2px ${color}`,
    elevationSmall: `0px 4px 8px ${_colors.black_16}`,
    elevationMedium: `0px 8px 16px ${_colors.black_16}`,
    elevationLarge: `0px 16px 32px ${_colors.black_16}`,
  },
});
